name       : perl-gettext
version    : 1.07
release    : 2
source     :
    - http://search.cpan.org/CPAN/authors/id/P/PV/PVANDRY/gettext-1.07.tar.gz : 909d47954697e7c04218f972915b787bd1244d75e3bd01620bc167d5bbc49c15
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Interface to gettext family of functions
description: "The gettext module permits access from perl to the gettext()\nfamily\
    \ of functions for retrieving message strings from databases \nconstructed to\
    \ internationalize software.\n"
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
