name       : perl-gettext
version    : 1.07
release    : 7
source     :
    - http://search.cpan.org/CPAN/authors/id/P/PV/PVANDRY/gettext-1.07.tar.gz : 909d47954697e7c04218f972915b787bd1244d75e3bd01620bc167d5bbc49c15
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Interface to gettext family of functions
description: |
     This is a Perl5 module quickly written to gain access to the C library functions for internatialization. They work just like the C versions of the "GNU gettext utilities."
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
